global proc float math_sum(float $input[])
{
    float $result = 0;
    for ($i = 0; $i < size($input); $i++)
    {
        $result += $input[$i];
    }
    return $result;
}

global proc float math_diff(float $input[])
{
    float $result = $input[0];
    for ($i = 1; $i < size($input); $i++)
    {
        $result -= $input[$i];
    }
    return $result;
}

global proc float math_multiply(float $input[])
{
    float $result = $input[0];
    float $current = $input[0];

    for ($i = 0; $i < size($input)-1; $i++)
    {
        
        for ($o = 1; $o < $input[$i+1]; $o++)
        {
            $result += $current;
        }
        $current = $result;
    }
    return $result;
}

global proc float math_divide(float $input[])
{
    float $result = $input[0];
    for ($i = 1; $i < size($input); $i++)
    {
        $result /= $input[$i];
    }
    return $result;
}

global proc float math_power(float $input[])
{
    float $result = $input[0];
    float $current = $input[0];

    for ($i = 0; $i < size($input)-1; $i++)
    {
        
        for ($o = 1; $o < $input[$i+1]; $o++)
        {
            $result *= $current;
        }
        $current = $result;
    }
    return $result;
}

global proc float math_mean(float $input[])
{
    float $result = 0;
    for ($i = 0; $i < size($input); $i++)
    {
        $result += $input[$i];
    }
    $result /= size($input);
    return $result;
}

global proc float math_median(float $input[])
{
    int $index = 0;
    float $result = 0;
    float $size = size($input);
    $input = sort($input);
    if ($size % 2 == 0)
    {
        $index = ($size/2);
        $result = ($input[$index]+$input[$index-1])/2;
    }
    else
    {
        $index = ($size-1)/2;
        $result = $input[$index];
    }
    return $result;
}


global proc CreateArray()
{
    float $xval = `floatField -q -v xfieldValue`;
    float $yval = `floatField -q -v yfieldValue`;
    string $op = `textField -q -tx fieldOperation`;
    float $arry[] = {$xval, $yval};

    Calculate($arry, $op);
}

global proc CalculatorUI()
{
    string $mWindow = "cWindow";

    if (`window -exists $mWindow`)
        deleteUI $mWindow;
    $mWindow = `window -title "Calculator"
            -widthHeight 200 300
            -resizeToFitChildren 1
            $mWindow`;
    gridLayout -numberOfColumns 3 -cellWidthHeight 150 50;
        text -label "Value";
        text -label "Operation";
        text -label "Value ";
        floatField -value 0 xfieldValue;
        textField -text "" fieldOperation;
        floatField -value 0 yfieldValue;
        text -label " ";
        button -label "GO!" -c "CreateArray()";
    showWindow $mWindow;
}

global proc Calculate(float $arry[], string $funct)
{
    float $result = 0;

    float $xValue = `floatField -q -v xfieldValue`;
    string $op = `textField -q -tx fieldOperation`;
    float $yValue = `floatField -q -v yfieldValue`;

    if($funct == "add"){
        for($i = 0; $i <size($arry); $i++)
        {
            print($arry[$i] + " + ");
        }
        print( " = " + math_sum($arry));
        $result = math_sum($arry);
    }
    else if($funct == "subtract"){
        for($i = 0; $i <size($arry); $i++)
        {
            print($arry[$i] + " - ");
        }
        print(" = " + math_diff($arry));
        $result = math_diff($arry);
    }
    else if($funct == "multiply"){
        for($i = 0; $i <size($arry); $i++)
        {
            print($arry[$i] + " x ");
        }
        print(" = " + math_multiply($arry));
        $result = math_multiply($arry);
    }
    else if($funct == "divide"){
        for($i = 0; $i <size($arry); $i++)
        {
            print($arry[$i] + " / ");
        }
        print(" = " + math_divide($arry));
        $result = math_divide($arry);
    }
    else if($funct == "power"){
        for($i = 0; $i <size($arry); $i++)
        {
            print($arry[$i] + " ^ ");
        }
        print(" = " + math_power($arry));
        $result = math_power($arry);
    }
    else if($funct == "mean"){
        print("The mean of ");
        for($i = 0; $i <size($arry); $i++)
        {
            print($arry[$i] + ", ");
        }
        print(" is " + math_mean($arry) );
        $result = math_mean($arry);
    }
    else if($funct == "median"){
        print("The median of ");
         for($i = 0; $i <size($arry); $i++)
        {
            print($arry[$i] + ", ");
        }
        print(" is " + math_median($arry));
        $result = math_median($arry);
    }
    else
    {
        print("function not recognized");
    }

    string $rtext = "" + $result;
    string $rWindow = "rWindow";
    if (`window -exists $rWindow`)
        deleteUI $rWindow;
    $rWindow = `window -title "Result"
            -widthHeight 100 50
            -resizeToFitChildren 1
            $rWindow`;
    gridLayout -numberOfColumns 2 -cellWidthHeight 50 50;
        text -label "Result:";
        text -label $rtext;
        
    showWindow $rWindow;
}

CalculatorUI;

Calculate({2,3,6}, "multiply");

